# Generated by Django 5.1.6 on 2025-08-16 20:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, null=True, verbose_name='توکن')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با 09 شروع شده و 11 رقم باشد', regex='^09\\d{9}$')], verbose_name='شماره تلفن')),
                ('code', models.SmallIntegerField(verbose_name='کد یکبار مصرف')),
                ('code_expiry', models.DateTimeField(default=datetime.datetime(2025, 8, 16, 20, 18, 17, 919530, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضای کد')),
            ],
            options={
                'verbose_name': 'رمز یکبار مصرف',
                'verbose_name_plural': ' احراز هویت Otp',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('frist_name', models.CharField(max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(max_length=30, verbose_name='نام خانوداگی')),
                ('email', models.EmailField(max_length=255, verbose_name='آدرس ایمیل ادمین')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='شماره تلفن ادمین')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('is_admin', models.BooleanField(default=False, verbose_name=' وضعیت دسترسی کامل ادمین')),
                ('cerated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('type', models.IntegerField(choices=[(1, 'superuser'), (2, 'admin'), (3, 'Limited_admin')], default=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
