# Generated by Django 5.1.6 on 2025-08-20 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_otp_code_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 15, 16, 43, 289640, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضای کد'),
        ),
    ]
