# Generated by Django 5.1.6 on 2025-08-25 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_otp_code_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 25, 16, 41, 14, 222806, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضای کد'),
        ),
    ]
