# Generated by Django 5.1.6 on 2025-08-25 17:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_otp_code_expiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'مدیریت کاربران '},
        ),
        migrations.RemoveField(
            model_name='user',
            name='cerated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='frist_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='created_dete',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 25, 17, 13, 30, 383486, tzinfo=datetime.timezone.utc), verbose_name='تاریخ ایجاد '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name=' تاریخ بروز رسانی'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 25, 17, 15, 12, 926952, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضای کد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'superuser'), (2, 'admin'), (3, 'limited_admin')], default=2, verbose_name='نقش کاربر'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام ')),
                ('last_name', models.CharField(max_length=50, verbose_name=' نام خانوداگی ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='تصویر پروفایل')),
                ('created_dete', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name=' تاریخ بروز رسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'مدیریت پروفایل ها ',
            },
        ),
    ]
