# Generated by Django 5.1.6 on 2025-09-04 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_options_remove_user_cerated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 4, 15, 38, 11, 106215, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضای کد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'مدیر ارشد'), (2, 'مدیر فروشگاه '), (3, 'کارمند محدود')], default=2, verbose_name='نقش کاربر'),
        ),
    ]
