# Generated by Django 5.1.6 on 2025-09-04 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_otp_code_expiry_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 4, 18, 21, 25, 29723, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضای کد'),
        ),
    ]
