# Generated by Django 5.1.6 on 2025-09-06 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_otp_code_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 6, 11, 9, 51, 615932, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضای کد'),
        ),
    ]
