# Generated by Django 5.1.6 on 2025-08-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created_at'], 'verbose_name': 'فروشگاه', 'verbose_name_plural': 'فروشگاه ها'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
