# Generated by Django 5.1.6 on 2025-09-06 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_category_options_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.CreateModel(
            name='StoreServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان خدمت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Store.storeservices', verbose_name='زیر دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی ',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='store_service',
            field=models.ManyToManyField(blank=True, related_name='product', to='Store.storeservices', verbose_name='عنوان خدمت فروشگاه'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_service',
            field=models.ManyToManyField(blank=True, related_name='store_service', to='Store.storeservices', verbose_name='خدمات فروشگاه'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
