# Generated by Django 5.1.6 on 2025-09-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_remove_product_category_storeservices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeservices',
            options={'ordering': ['created_at'], 'verbose_name': 'نوع خدمت', 'verbose_name_plural': 'خدمات ارائه شده'},
        ),
        migrations.RemoveField(
            model_name='store',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='store',
            name='longitude',
        ),
        migrations.AddField(
            model_name='store',
            name='location_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='موقعیت/لوکشین'),
        ),
    ]
