# Generated by Django 5.1.6 on 2025-08-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(verbose_name='شماره فاکتور ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ فاکتور')),
                ('nots', models.TextField(blank=True, null=True, verbose_name='توضیحات اختیاری')),
            ],
            options={
                'verbose_name': 'صورتحساب',
                'verbose_name_plural': 'فاکتور ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('car', models.CharField(blank=True, max_length=120, null=True, verbose_name='خودرو ')),
                ('car_model', models.CharField(blank=True, max_length=120, null=True, verbose_name='مدل ماشین')),
                ('current_km', models.FloatField(blank=True, max_length=120, null=True, verbose_name=' کیلومتر فعلی')),
                ('next_km', models.FloatField(blank=True, null=True, verbose_name='تاریخ نوبت بعدی')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='تعداد محصول')),
                ('product_total', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت مجموع محصولات')),
                ('service_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت سرویس ')),
                ('amount_total', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خدمت')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['-created_at'],
            },
        ),
    ]
