# Generated by Django 5.1.6 on 2025-08-16 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Services', '0001_initial'),
        ('Store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sold_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_sold', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده'),
        ),
        migrations.AddField(
            model_name='services',
            name='product',
            field=models.ManyToManyField(related_name='service', to='Store.product', verbose_name='محصولات'),
        ),
        migrations.AddField(
            model_name='services',
            name='sold_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_sold', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده'),
        ),
        migrations.AddField(
            model_name='services',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='Store.store', verbose_name='فروشگاه '),
        ),
        migrations.AddField(
            model_name='invoice',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costumer', to='Services.services', verbose_name='شماره تماس مشتری'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='Services.services', verbose_name='خدمات '),
        ),
    ]
