# Generated by Django 5.1.6 on 2025-08-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image_km',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر کیلومتر '),
        ),
        migrations.AddField(
            model_name='services',
            name='image_plaque',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر پلاک'),
        ),
        migrations.AddField(
            model_name='services',
            name='plaque',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره پلاک'),
        ),
    ]
