# Generated by Django 5.1.6 on 2025-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_services_image_km_services_image_plaque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='phone',
            new_name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='services',
            name='phone',
        ),
        migrations.AddField(
            model_name='services',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس مشتری'),
        ),
    ]
