# Generated by Django 5.1.6 on 2025-08-25 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_rename_phone_invoice_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-created_at'], 'verbose_name': 'خدمت', 'verbose_name_plural': 'سرویس ها'},
        ),
        migrations.AddField(
            model_name='services',
            name='color',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='رنگ خودرو'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costumer', to='Services.services', verbose_name='شماره تماس مشتری'),
        ),
        migrations.AlterField(
            model_name='services',
            name='car_model',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='مدل خودرو '),
        ),
    ]
