# Generated by Django 5.1.6 on 2025-09-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_alter_services_options_services_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='color',
            field=models.CharField(blank=True, choices=[('white', 'سفید'), ('black', 'مشکی'), ('silver', 'نقره\u200cای'), ('gray', 'خاکستری (ذغالی)'), ('blue', 'آبی'), ('navy', 'سرمه\u200cای'), ('red', 'قرمز'), ('green', 'سبز (یشمی/زیتونی)'), ('beige', 'بژ (طلایی/کرم)')], max_length=40, null=True, verbose_name='رنگ خودرو'),
        ),
        migrations.AlterField(
            model_name='services',
            name='next_km',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='تاریخ نوبت بعدی'),
        ),
    ]
