# Generated by Django 5.1.6 on 2025-09-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_alter_services_color_alter_services_next_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='color',
            field=models.CharField(blank=True, choices=[('white', 'سفید'), ('black', 'مشکی'), ('silver', 'نقره\u200cای'), ('gray', 'خاکستری (ذغالی)'), ('blue', 'سرمه\u200cای'), ('navy', 'آبی'), ('red', 'قرمز'), ('green', 'سبز (یشمی/زیتونی)'), ('beige', 'بژ (طلایی/کرم)')], max_length=40, null=True, verbose_name='رنگ خودرو'),
        ),
    ]
